
package jaxb;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Gerador", targetNamespace = "http://jaxb/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Gerador {


    /**
     * 
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "geraNumero", targetNamespace = "http://jaxb/", className = "jaxb.GeraNumero")
    @ResponseWrapper(localName = "geraNumeroResponse", targetNamespace = "http://jaxb/", className = "jaxb.GeraNumeroResponse")
    @Action(input = "http://jaxb/Gerador/geraNumeroRequest", output = "http://jaxb/Gerador/geraNumeroResponse")
    public double geraNumero();

}
