
package jaxb;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GeradorService", targetNamespace = "http://jaxb/", wsdlLocation = "http://localhost:8080/gerador?wsdl")
public class GeradorService
    extends Service
{

    private final static URL GERADORSERVICE_WSDL_LOCATION;
    private final static WebServiceException GERADORSERVICE_EXCEPTION;
    private final static QName GERADORSERVICE_QNAME = new QName("http://jaxb/", "GeradorService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/gerador?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GERADORSERVICE_WSDL_LOCATION = url;
        GERADORSERVICE_EXCEPTION = e;
    }

    public GeradorService() {
        super(__getWsdlLocation(), GERADORSERVICE_QNAME);
    }

    public GeradorService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GERADORSERVICE_QNAME, features);
    }

    public GeradorService(URL wsdlLocation) {
        super(wsdlLocation, GERADORSERVICE_QNAME);
    }

    public GeradorService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GERADORSERVICE_QNAME, features);
    }

    public GeradorService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GeradorService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Gerador
     */
    @WebEndpoint(name = "GeradorPort")
    public Gerador getGeradorPort() {
        return super.getPort(new QName("http://jaxb/", "GeradorPort"), Gerador.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Gerador
     */
    @WebEndpoint(name = "GeradorPort")
    public Gerador getGeradorPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://jaxb/", "GeradorPort"), Gerador.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GERADORSERVICE_EXCEPTION!= null) {
            throw GERADORSERVICE_EXCEPTION;
        }
        return GERADORSERVICE_WSDL_LOCATION;
    }

}
